import { Translation } from './types';

export const ODISHA_DISTRICTS = [
  { id: 'dist_angul', key: 'Angul' },
  { id: 'dist_balangir', key: 'Balangir' },
  { id: 'dist_balasore', key: 'Balasore' },
  { id: 'dist_bargarh', key: 'Bargarh' },
  { id: 'dist_bhadrak', key: 'Bhadrak' },
  { id: 'dist_boudh', key: 'Boudh' },
  { id: 'dist_cuttack', key: 'Cuttack' },
  { id: 'dist_deogarh', key: 'Deogarh' },
  { id: 'dist_dhenkanal', key: 'Dhenkanal' },
  { id: 'dist_gajapati', key: 'Gajapati' },
  { id: 'dist_ganjam', key: 'Ganjam' },
  { id: 'dist_jagatsinghapur', key: 'Jagatsinghapur' },
  { id: 'dist_jajpur', key: 'Jajpur' },
  { id: 'dist_jharsuguda', key: 'Jharsuguda' },
  { id: 'dist_kalahandi', key: 'Kalahandi' },
  { id: 'dist_kandhamal', key: 'Kandhamal' },
  { id: 'dist_kendrapara', key: 'Kendrapara' },
  { id: 'dist_kendujhar', key: 'Kendujhar' },
  { id: 'dist_khordha', key: 'Khordha' },
  { id: 'dist_koraput', key: 'Koraput' },
  { id: 'dist_malkangiri', key: 'Malkangiri' },
  { id: 'dist_mayurbhanj', key: 'Mayurbhanj' },
  { id: 'dist_nabarangpur', key: 'Nabarangpur' },
  { id: 'dist_nayagarh', key: 'Nayagarh' },
  { id: 'dist_nuapada', key: 'Nuapada' },
  { id: 'dist_puri', key: 'Puri' },
  { id: 'dist_rayagada', key: 'Rayagada' },
  { id: 'dist_sambalpur', key: 'Sambalpur' },
  { id: 'dist_subarnapur', key: 'Subarnapur' },
  { id: 'dist_sundargarh', key: 'Sundargarh' }
];

export const SKILLS = [
  { id: 'skill_ac', key: 'AC Repair', icon: 'fa-snowflake', bg: 'bg-cyan-50', color: 'text-cyan-600', desc: 'Air conditioning installation and repair' },
  { id: 'skill_carwash', key: 'Car Wash', icon: 'fa-car-side', bg: 'bg-blue-50', color: 'text-blue-600', desc: 'Professional car washing and detailing' },
  { id: 'skill_cleaning', key: 'Cleaner', icon: 'fa-broom', bg: 'bg-teal-50', color: 'text-teal-600', desc: 'Professional house cleaning and maintenance' },
  { id: 'skill_cook', key: 'Cook', icon: 'fa-utensils', bg: 'bg-orange-50', color: 'text-orange-600', desc: 'Experienced cooks for home cooking' },
  { id: 'skill_driver', key: 'Driver', icon: 'fa-steering-wheel', bg: 'bg-indigo-50', color: 'text-indigo-600', desc: 'Reliable drivers for personal or commercial' },
  { id: 'skill_electrician', key: 'Electrician', icon: 'fa-bolt', bg: 'bg-amber-50', color: 'text-amber-600', desc: 'Licensed electricians for all electrical' },
  { id: 'skill_gardener', key: 'Gardener', icon: 'fa-seedling', bg: 'bg-green-50', color: 'text-green-600', desc: 'Garden maintenance and landscaping' },
  { id: 'skill_helper', key: 'Helper', icon: 'fa-hands-holding', bg: 'bg-blue-50', color: 'text-blue-600', desc: 'General household helpers for daily tasks' },
  { id: 'skill_mason', key: 'Mason', icon: 'fa-trowel-bricks', bg: 'bg-emerald-50', color: 'text-emerald-600', desc: 'Skilled masons for construction and repair' },
  { id: 'skill_mechanic', key: 'Mechanic', icon: 'fa-tools', bg: 'bg-rose-50', color: 'text-rose-600', desc: 'Auto mechanics for vehicle repair' },
  { id: 'skill_nurse', key: 'Nurse', icon: 'fa-user-nurse', bg: 'bg-sky-50', color: 'text-sky-600', desc: 'Qualified nurses for home healthcare' },
  { id: 'skill_painter', key: 'Painter', icon: 'fa-paint-roller', bg: 'bg-purple-50', color: 'text-purple-600', desc: 'Interior and exterior painting services' }
];

export const DECLINE_REASONS = [
  'Incomplete Documents',
  'Blurred/Unreadable Photos',
  'Invalid ID Proof',
  'Skill Verification Failed',
  'Location mismatch',
  'Inappropriate Profile Content'
];

export const TRANSLATIONS: Translation = {
  app_name: { EN: 'MajdoorLink', OR: 'ମଜଦୁର ଲିଙ୍କ', HI: 'मजदूर लिंक' },
  hero_title_line_1: { EN: 'Skilled Service Experts', OR: 'ଦକ୍ଷ ସେବା ବିଶେଷଜ୍ଞ', HI: 'कुशल सेवा विशेषज्ञ' },
  hero_title_line_2: { EN: 'Linked to Your Doorstep', OR: 'ଆପଣଙ୍କ ଦ୍ୱାର ଦେଶରେ', HI: 'आपके घर के दरवाजे पर' },
  hero_subtitle: { EN: 'The most trusted platform to book verified electricians, plumbers, and masons in Odisha. Guaranteed safety at standard market rates.', OR: 'ଓଡ଼ିଶାରେ ଯାଞ୍ଚ ହୋଇଥିବା ଶ୍ରମିକମାନଙ୍କୁ ବୁକ୍ କରିବା ପାଇଁ ସବୁଠାରୁ ବିଶ୍ୱସ୍ତ ପ୍ଲାଟଫର୍ମ |', HI: 'ओडिशा में सत्यापित कर्मचारियों को बुक करने के लिए सबसे भरोसेमंद मंच।' },
  hero_highlight: { EN: 'Directly', OR: 'ସିଧାସଳଖ', HI: 'सीधे' },
  hero_reassurance: { EN: 'Government ID Verified • No Upfront Payment • All 30 Districts', OR: 'ପରିଚୟ ପତ୍ର ଯାଞ୍ଚ ହୋଇଛି • ସମସ୍ତ ୩୦ ଜିଲ୍ଲା', HI: 'आईडी सत्यापित • कोई अग्रिम भुगतान नहीं • सभी 30 जिले' },
  find_worker_cta: { EN: 'Hire a Professional', OR: 'ବିଶେଷଜ୍ଞଙ୍କୁ ନିଯୁକ୍ତ କରନ୍ତୁ', HI: 'विशेषज्ञ को काम पर रखें' },
  become_worker_cta: { EN: 'Join as a Partner', OR: 'ପାର୍ଟନର ଭାବେ ଯୋଗ ଦିଅନ୍ତୁ', HI: 'पार्टनर के रूप में जुड़ें' },
  trusted_badge: { EN: 'Trusted by 10,000+ Families in Odisha', OR: 'ଓଡ଼ିଶାର ୧୦,୦୦୦+ ପରିବାର ଦ୍ୱାରା ବିଶ୍ୱସ୍ତ', HI: 'ओडिशा के 10,000+ परिवारों द्वारा विश्वसनीय' },
  our_services: { EN: 'Our Services', OR: 'ଆମର ସେବା', HI: 'हमारी सेवाएँ' },
  featured_workers: { EN: 'Featured Workers', OR: 'ପ୍ରମୁଖ ଶ୍ରମିକ', HI: 'प्रमुख श्रमिक' },
  how_it_works: { EN: 'How It Works', OR: 'ଏହା କିପରି କାମ କରେ', HI: 'यह कैसे काम करता है' },
  login: { EN: 'Login', OR: 'ଲଗଇନ୍', HI: 'लॉगिन' },
  register: { EN: 'Register', OR: 'ପଞ୍ଜୀକରଣ', HI: 'रजिस्टर' },
  admin: { EN: 'Admin', OR: 'ପ୍ରଶାସକ', HI: 'एडमिन' },
  district: { EN: 'District', OR: 'ଜିଲ୍ଲା', HI: 'जिला' },
  skill: { EN: 'Skill', OR: 'ଦକ୍ଷତା', HI: 'कौशल' },
  search: { EN: 'Search', OR: 'ଖୋଜନ୍ତୁ', HI: 'खोजें' },
  my_dashboard: { EN: 'Dashboard', OR: 'ଡ୍ୟାଶବୋର୍ଡ', HI: 'डैशबोर्ड' },
  all_odisha: { EN: 'All Odisha', OR: 'ସମଗ୍ର ଓଡ଼ିଶା', HI: 'पूरा ओडिशा' },
  any_skill: { EN: 'Any Skill', OR: 'ଯେକୌଣସି ଦକ୍ଷତା', HI: 'कोई भी कौशल' },
  verified: { EN: 'Verified', OR: 'ଯାଞ୍ach ହୋଇଛି', HI: 'सत्यापित' },
  hire_now: { EN: 'Hire Now', OR: 'ଏବେ ନିଯୁକ୍ତ କରନ୍ତୁ', HI: 'अभी नियुक्त करें' },
  phone_label: { EN: 'Mobile Number', OR: 'ମୋବାଇଲ୍ ନମ୍ବର', HI: 'मोबाइल नंबर' },
  phone_placeholder: { EN: '10-digit mobile number', OR: '୧୦-ଅଙ୍କ ବିଶିଷ୍ଟ ନମ୍ବର', HI: '10-अंकों का नंबर' },
  full_name: { EN: 'Full Name', OR: 'ପୁରା ନାମ', HI: 'पूरा नाम' },
  email_address: { EN: 'Email Address', OR: 'ଇମେଲ୍ ଠିକଣା', HI: 'ईमेल पता' },
  password: { EN: 'Password', OR: 'ପାସୱାର୍ଡ', HI: 'पासवर्ड' },
  confirm_password: { EN: 'Confirm Password', OR: 'ପାସୱାର୍ଡ ନିଶ୍ଚିତ କରନ୍ତୁ', HI: 'पासवर्ड की पुष्टि करें' },
  create_account: { EN: 'Create Account', OR: 'ଆକାଉଣ୍ଟ୍ ତିଆରି କରନ୍ତୁ', HI: 'खाता बनाएं' },
  join_as: { EN: 'I want to...', OR: 'ମୁଁ ଚାହୁଁଛି...', HI: 'मैं चाहता हूँ...' },
  cust_role: { EN: 'Hire Workers', OR: 'ଶ୍ରମିକ ଖୋଜନ୍ତୁ', HI: 'कामगार खोजें' },
  work_role: { EN: 'Find Work', OR: 'କାମ ଖୋଜନ୍ତୁ', HI: 'काम खोजें' },
  back: { EN: 'Back', OR: 'ପଛକୁ', HI: 'पीछे' },
  sign_in: { EN: 'Sign In', OR: 'ସାଇନ୍ ଇନ୍', HI: 'साइन इन' },
  find_worker: { EN: 'Find a Worker', OR: 'ଶ୍ରମିକ ଖୋଜନ୍ତୁ', HI: 'कामगार खोजें' },
  book_now: { EN: 'Book Now', OR: 'ବୁକ୍ କରନ୍ତୁ', HI: 'बुक करें' },
  availability: { EN: 'Availability', OR: 'ଉପଲବ୍ଧତା', HI: 'उपलब्धता' },
  full_day: { EN: 'Full Day', OR: 'ପୁରା ଦିନ', HI: 'पूरा दिन' },
  morning: { EN: 'Morning', OR: 'ସକାଳ', HI: 'सुबह' },
  evening: { EN: 'Evening', OR: 'ସନ୍ଧ୍ୟା', HI: 'शाम' },
  rest: { EN: 'Rest Day', OR: 'ଛୁଟି ଦିନ', HI: 'आराम का दिन' },
  odisha_digital_hub: { EN: "Odisha's Digital Skilled Hub", OR: 'ଓଡ଼ିଶାର ଡିଜିଟାଲ୍ ଦକ୍ଷତା ହବ୍', HI: 'ओडिशा का डिजिटल स्किल हब' },
  more: { EN: 'More', OR: 'ଅଧିକ', HI: 'अधिक' },
  top_rated_badge: { EN: 'Top Rated Workers', OR: 'ଶ୍ରେଷ୍ଠ ଶ୍ରମିକ', HI: 'टॉप रेटेड कामगार' },
  featured_title: { EN: 'Meet Our Featured Professionals', OR: 'ଆମର ପ୍ରମୁଖ ବିଶେଷଜ୍ଞଙ୍କୁ ଭେଟନ୍ତୁ', HI: 'हमारे प्रमुख पेशेवरों से मिलें' },
  featured_subtitle: { EN: 'Highly skilled and verified workers trusted by thousands of customers', OR: 'ଓଡ଼ିଶାର ହଜାର ହଜାର ଗ୍ରାହକଙ୍କ ଦ୍ୱାରା ବିଶ୍ୱସ୍ତ ଦକ୍ଷ ଏବଂ ଯାଞ୍ଚ ହୋଇଥିବା ଶ୍ରମିକ', HI: 'हजारों ग्राहकों द्वारा विश्वसनीय उच्च कुशल और सत्यापित श्रमिक' },
  exp_years: { EN: 'years', OR: 'ବର୍ଷ', HI: 'वर्ष' },
  jobs_done: { EN: 'jobs', OR: 'କାମ', HI: 'काम' },
  new_partner: { EN: 'New Partner', OR: 'ନୂଆ ପାର୍ଟନର', HI: 'नया पार्टनर' },
  verification_in_progress: { EN: 'Verification in progress', OR: 'ଯାଞ୍ଚ ଚାଲିଛି', HI: 'सत्यापन जारी है' },
  'Popular Services': { EN: 'Popular Services', OR: 'ଲୋକପ୍ରିୟ ସେବା', HI: 'लोकप्रिय सेवाएँ' },
  'Most requested services by our clients': { EN: 'Most requested services by our clients', OR: 'ଆମ ଗ୍ରାହକଙ୍କ ଦ୍ୱାରା ସବୁଠାରୁ ଅଧିକ ଅନୁରୋଧିତ ସେବା', HI: 'हमारे ग्राहकों द्वारा सबसे अधिक मांग वाली सेवाएँ' },
  'Hire a Worker': { EN: 'Hire a Worker', OR: 'ଶ୍ରମିକ ନିଯୁକ୍ତ କରନ୍ତୁ', HI: 'एक कामगार नियुक्त करें' },
  'Find skilled professionals for your needs': { EN: 'Find skilled professionals for your needs', OR: 'ଆପଣଙ୍କ ଆବଶ୍ୟକତା ପାଇଁ ଦକ୍ଷ ବିଶେଷଜ୍ଞ ଖୋଜନ୍ତୁ', HI: 'अपनी जरूरतों के लिए कुशल पेशेवर खोजें' },
  'What service do you need?': { EN: 'What service do you need?', OR: 'ଆପଣଙ୍କୁ କେଉଁ ସେବା ଦରକାର?', HI: 'आपको किस सेवा की आवश्यकता है?' },
  'Connect with trusted professionals in your area for any service requirement': { EN: 'Connect with trusted professionals in your area for any service requirement', OR: 'ଯେକୌଣସି ସେବା ଆବଶ୍ୟକତା ପାଇଁ ଆପଣଙ୍କ ଅଞ୍ଚଳରେ ବିଶ୍ୱସ୍ତ ବିଶେଷଜ୍ଞଙ୍କ ସହ ସଂଯୋଗ କରନ୍ତୁ', HI: 'किसी भी सेवा आवश्यकता के लिए अपने क्षेत्र के विश्वसनीय पेशेवरों से जुड़ें' },
  'Quick Service Search': { EN: 'Quick Service Search', OR: 'କ୍ୱିକ୍ ସର୍ଭିସ୍ ସର୍ଚ୍ଚ', HI: 'त्वरित सेवा खोज' },
  'Type to search services...': { EN: 'Type to search services...', OR: 'ସେବା ଖୋଜିବା ପାଇଁ ଟାଇପ୍ କରନ୍ତୁ...', HI: 'सेवाएं खोजने के लिए टाइप करें...' },
  'Namaskar': { EN: 'Namaskar', OR: 'ନମସ୍କାର', HI: 'नमस्ते' },
  'Platform Usage': { EN: 'Platform Usage', OR: 'ପ୍ଲାଟଫର୍ମ ବ୍ୟବହାର', HI: 'प्लेटफॉर्म का उपयोग' },
  'Total Bookings': { EN: 'Total Bookings', OR: 'ସମୁଦାୟ ବୁକିଂ', HI: 'कुल बुकिंग' },
  'Ongoing Jobs': { EN: 'Ongoing Jobs', OR: 'ଚାଲୁଥିବା କାମ', HI: 'जारी कार्य' },
  'Completed': { EN: 'Completed', OR: 'ସମାପ୍ତ', HI: 'पूरा हुआ' },
  'Booking History': { EN: 'Booking History', OR: 'ବୁକିଂ ଇତିହାସ', HI: 'बुकिंग इतिहास' },
  'No Service History': { EN: 'No Service History', OR: 'କୌଣସି ବୁକିଂ ଇତିହାସ ନାହିଁ', HI: 'कोई सेवा इतिहास नहीं' },
  'Ready to get your home repairs handled by trusted local professionals?': { EN: 'Ready to get your home repairs handled by trusted local professionals?', OR: 'ବିଶ୍ୱସ୍ତ ସ୍ଥାନୀୟ ବିଶେଷଜ୍ଞଙ୍କ ଦ୍ୱାରା ଆପଣଙ୍କ ଘର ମରାମତି ପାଇଁ ପ୍ରସ୍ତୁତ କି?', HI: 'विश्वसनीय स्थानीय पेशेवरों द्वारा अपने घर की मरम्मत कराने के लिए तैयार हैं?' },
  'Browse Specialist Network': { EN: 'Browse Specialist Network', OR: 'ବିଶେଷଜ୍ଞ ନେଟୱାର୍କ ଖୋଜନ୍ତୁ', HI: 'विशेषज्ञ नेटवर्क ब्राउज़ करें' },
  'Search for a specific service': { EN: 'Search for a specific service', OR: 'ଏକ ନିର୍ଦ୍ଦିଷ୍ଟ ସେବା ଖୋଜନ୍ତୁ', HI: 'एक विशिष्ट सेवा के लिए खोजें' },
  'AC Repair': { EN: 'AC Repair', OR: 'ଏସି ମରାମତି', HI: 'एसी मरम्मत' },
  'Car Wash': { EN: 'Car Wash', OR: 'ଗାଡି ସଫେଇ', HI: 'गाड़ी धुलाई' },
  'Cleaner': { EN: 'Cleaner', OR: 'ସଫେଇ କର୍ମଚାରୀ', HI: 'सफाई कर्मचारी' },
  'Cook': { EN: 'Cook', OR: 'ରୋଷେଇଆ', HI: 'रसोइया' },
  'Driver': { EN: 'Driver', OR: 'ଡ୍ରାଇଭର', HI: 'ड्राइवर' },
  'Electrician': { EN: 'Electrician', OR: 'ବିଦ୍ୟୁତ୍ ମିସ୍ତ୍ରୀ', HI: 'इलेक्ट्रीशियन' },
  'Gardener': { EN: 'Gardener', OR: 'ମାଳୀ', HI: 'माली' },
  'Helper': { EN: 'Helper', OR: 'ସହାୟକ', HI: 'सहायक' },
  'Mason': { EN: 'Mason', OR: 'ରାଜମିସ୍ତ୍ରୀ', HI: 'राजमिस्त्री' },
  'Mechanic': { EN: 'Mechanic', OR: 'ମେକାନିକ୍', HI: 'मैकेनिक' },
  'Nurse': { EN: 'Nurse', OR: 'ନର୍ସ', HI: 'नर्स' },
  'Painter': { EN: 'Painter', OR: 'ପେଣ୍ଟର', HI: 'पेंटर' },
  'Angul': { EN: 'Angul', OR: 'ଅନୁଗୋଳ', HI: 'अनुगुल' },
  'Balangir': { EN: 'Balangir', OR: 'ବଲାଙ୍ଗୀର', HI: 'बलांगीर' },
  'Balasore': { EN: 'Balasore', OR: 'ବାଲେଶ୍ୱର', HI: 'ବାଲେଶ୍ୱର' },
  'Bargarh': { EN: 'Bargarh', OR: 'ବରଗଡ଼', HI: 'बरगढ़' },
  'Bhadrak': { EN: 'Bhadrak', OR: 'ଭଦ୍ରକ', HI: 'भद्रक' },
  'Boudh': { EN: 'Boudh', OR: 'ବୌଦ୍ଧ', HI: 'बौध' },
  'Cuttack': { EN: 'Cuttack', OR: 'କଟକ', HI: 'कटक' },
  'Deogarh': { EN: 'Deogarh', OR: 'ଦେବଗଡ଼', HI: 'देवगढ़' },
  'Dhenkanal': { EN: 'Dhenkanal', OR: 'ଢେଙ୍କାନାଳ', HI: 'ढेकानाल' },
  'Gajapati': { EN: 'Gajapati', OR: 'ଗଜପତି', HI: 'गजपति' },
  'Ganjam': { EN: 'Ganjam', OR: 'ଗଞ୍ଜାମ', HI: 'गंजाम' },
  'Jagatsinghapur': { EN: 'Jagatsinghapur', OR: 'ଜଗତସିଂହପୁର', HI: 'जगतसिंहपुर' },
  'Jajpur': { EN: 'Jajpur', OR: 'ଯାଜପୁର', HI: 'जाजपुर' },
  'Jharsuguda': { EN: 'Jharsuguda', OR: 'ଝାରସୁଗୁଡ଼ା', HI: 'झारसुगुड़ा' },
  'Kalahandi': { EN: 'Kalahandi', OR: 'କଳାହାଣ୍ଧି', HI: 'कालाहांडी' },
  'Kandhamal': { EN: 'Kandhamal', OR: 'କନ୍ଧମାଳ', HI: 'कंधमाल' },
  'Kendrapara': { EN: 'Kendrapara', OR: 'କେନ୍ଦ୍ରାପଡ଼ା', HI: 'केंद्रपाड़ा' },
  'Kendujhar': { EN: 'Kendujhar', OR: 'କେନ୍ଦୁଝର', HI: 'क्योंझर' },
  'Khordha': { EN: 'Khordha', OR: 'ଖୋର୍ଦ୍ଧା', HI: 'खोरधा' },
  'Koraput': { EN: 'Koraput', OR: 'କୋରାପୁଟ', HI: 'कोरापुट' },
  'Malkangiri': { EN: 'Malkangiri', OR: 'ମାଲକାନଗିରି', HI: 'मलकानगिरी' },
  'Mayurbhanj': { EN: 'Mayurbhanj', OR: 'ମୟୂରଭଞ୍ଜ', HI: 'मयूरभंज' },
  'Nabarangpur': { EN: 'Nabarangpur', OR: 'ନବରଙ୍ଗପୁର', HI: 'नवरंगपुर' },
  'Nayagarh': { EN: 'Nayagarh', OR: 'ନୟାଗଡ଼', HI: 'नयागढ़' },
  'Nuapada': { EN: 'Nuapada', OR: 'ନୂଆପଡ଼ା', HI: 'नुआपाड़ा' },
  'Puri': { EN: 'Puri', OR: 'ପୁରୀ', HI: 'पुरी' },
  'Rayagada': { EN: 'Rayagada', OR: 'ରାୟଗଡ଼ା', HI: 'रायगड़ा' },
  'Sambalpur': { EN: 'Sambalpur', OR: 'ସମ୍ବଲପୁର', HI: 'संबलपुर' },
  'Subarnapur': { EN: 'Subarnapur', OR: 'ସୁବର୍ଣ୍ଣପୁର', HI: 'सुवर्णपुर' },
  'Sundargarh': { EN: 'Sundargarh', OR: 'ସୁନ୍ଦରଗଡ଼', HI: 'सुंदरगढ़' },
  growth_story_label: { EN: 'Growth Story', OR: 'ଅଭିବୃଦ୍ଧି କାହାଣୀ', HI: 'विकास की कहानी' },
  digitizing_odisha_title: { EN: "Digitizing Odisha's Skilled Workforce", OR: 'ଓଡ଼ିଶାର ଦକ୍ଷ ଶ୍ରମିକମାନଙ୍କର ଡିଜିଟାଇଜେସନ୍', HI: 'ओडिशा के कुशल कार्यबल का डिजिटलीकरण' },
  mission_desc: { EN: 'We are on a mission to bring financial inclusion and digital identity to 100,000+ local masons, plumbers, and helpers across all districts.', OR: 'ଆମେ ସମସ୍ତ ଜିଲ୍ଲାର ୧,୦୦,୦୦୦+ ସ୍ଥାନୀୟ ରାଜମିସ୍ତ୍ରୀ, ପ୍ଲମ୍ବର ଏବଂ ସହାୟକମାନଙ୍କୁ ଆର୍ଥିକ ଅନ୍ତର୍ଭୁକ୍ତିକରଣ ଏବଂ ଡିଜିଟାଲ୍ ପରିଚୟ ପ୍ରଦାନ କରିବାକୁ ଲକ୍ଷ୍ୟ ରଖିଛୁ।', HI: 'हम सभी जिलों में 100,000+ स्थानीय राजमिस्त्रियों, प्लंबरों और सहायकों को वित्तीय समावेशन और डिजिटल पहचान दिलाने के मिशन पर हैं।' },
  view_impact_report: { EN: 'View Impact Report', OR: 'ପ୍ରଭାବ ରିପୋର୍ଟ ଦେଖନ୍ତୁ', HI: 'इम्पैक्ट रिपोर्ट देखें' },
  districts_covered: { EN: 'Districts Covered', OR: 'ଜିଲ୍ଲା ଅନ୍ତର୍ଭୁକ୍ତ', HI: 'शामिल जिले' },
  jobs_created: { EN: 'Jobs Created', OR: 'ନିଯୁକ୍ତି ସୃଷ୍ଟି', HI: 'सृजित नौकरियां' },
  worker_earnings: { EN: 'Worker Earnings', OR: 'ଶ୍ରମିକଙ୍କ ଆୟ', HI: 'श्रमिक की कमाई' },
  safety_rating: { EN: 'Safety Rating', OR: 'ସୁରକ୍ଷା ରେଟିଂ', HI: 'सुरक्षा रेटिंग' },
  top_rated_experts: { EN: 'Top Rated Experts', OR: 'ଶ୍ରେଷ୍ଠ ବିଶେଷଜ୍ଞ', HI: 'टॉप रेटेड विशेषज्ञ' },
  meet_verified_title: { EN: 'Meet Verified Professionals', OR: 'ଯାଞ୍ଚ ହୋଇଥିବା ବିଶେଷଜ୍ଞଙ୍କୁ ଭେଟନ୍ତୁ', HI: 'सत्यापित पेशेवरों से मिलें' },
  meet_verified_subtitle: { EN: 'Highly skilled workers trusted by thousands across the state', OR: 'ରାଜ୍ୟର ହଜାର ହଜାର ଲୋକଙ୍କ ଦ୍ୱାରା ବିଶ୍ୱସ୍ତ ଦକ୍ଷ ଶ୍ରମିକ', HI: 'राज्य भर में हजारों लोगों द्वारा भरोसेमंद अत्यधिक कुशल श्रमिक' },
  seamless_process: { EN: 'Seamless Process', OR: 'ନିରନ୍ତର ପ୍ରକ୍ରିୟା', HI: 'निर्बाध प्रक्रिया' },
  how_it_works_subtitle: { EN: 'Get your home service done in three simple steps', OR: 'ତିନୋଟି ସରଳ ପଦକ୍ଷେପରେ ଆପଣଙ୍କର ଘରୋଇ ସେବା ପାଆନ୍ତୁ', HI: 'तीन सरल चरणों में अपनी घरेलू सेवा प्राप्त करें' },
  Search: { EN: 'Search', OR: 'ଖୋଜନ୍ତୁ', HI: 'खोजें' },
  Connect: { EN: 'Connect', OR: 'ସଂଯୋଗ କରନ୍ତୁ', HI: 'जुड़ें' },
  'Get Work Done': { EN: 'Get Work Done', OR: 'କାମ କରନ୍ତୁ', HI: 'काम करवाएं' },
  step_1_desc: { EN: 'Choose from 12+ categories and filter by your Odisha district.', OR: '୧୨+ ବର୍ଗରୁ ବାଛନ୍ତୁ ଏବଂ ଆପଣଙ୍କ ଓଡ଼ିଶା ଜିଲ୍ଲା ଅନୁସାରେ ଫିଲ୍ଟର୍ କରନ୍ତୁ।', HI: '12+ श्रेणियों में से चुनें और अपने ओडिशा जिले के अनुसार फ़िल्टर करें।' },
  step_2_desc: { EN: 'Review worker profiles, check pricing, and send a booking request.', OR: 'ଶ୍ରମିକ ପ୍ରୋଫାଇଲ୍ ଦେଖନ୍ତୁ, ମୂଲ୍ୟ ଯାଞ୍ଚ କରନ୍ତୁ ଏବଂ ବୁକିଂ ଅନୁରୋଧ ପଠାନ୍ତୁ।', HI: 'श्रमिक प्रोफाइल की समीक्षा करें, मूल्य निर्धारण की जांच करें और बुकिंग अनुरोध भेजें।' },
  step_3_desc: { EN: 'Worker arrives at your doorstep, verify their ID, and pay after completion.', OR: 'ଶ୍ରମିକ ଆପଣଙ୍କ ଦ୍ୱାରରେ ପହଞ୍ଚିବେ, ପରିଚୟ ପତ୍ର ଯାଞ୍ଚ କରନ୍ତୁ ଏବଂ କାମ ସରିବା ପରେ ଦେୟ ଦିଅନ୍ତୁ।', HI: 'कर्मचारी आपके दरवाजे पर पहुंचेगा, उनकी आईडी सत्यापित करें और पूरा होने के बाद भुगतान करें।' },
  safety_priority_title: { EN: 'Your Safety is Our Top Priority', OR: 'ଆପଣଙ୍କ ସୁରକ୍ଷା ଆମର ସର୍ବୋଚ୍ଚ ପ୍ରାଥମିକତା', HI: 'आपकी सुरक्षा हमारी सर्वोच्च प्राथमिकता है' },
  safety_priority_desc: { EN: "In Odisha, community trust is everything. That's why every single professional on MajdoorLink must undergo a physical document verification process before getting their first assignment.", OR: 'ଓଡ଼ିଶାରେ ସାମାଜିକ ବିଶ୍ୱାସ ହିଁ ସବୁକିଛି। ସେଥିପାଇଁ ମଜଦୁର ଲିଙ୍କରେ ପ୍ରତ୍ୟେକ ବିଶେଷଜ୍ଞଙ୍କୁ ସେମାନଙ୍କର ପ୍ରଥମ କାମ ପୂର୍ବରୁ ଶାରୀରିକ ଦଲିଲ ଯାଞ୍ଚ ପ୍ରକ୍ରିୟା ଦେଇ ଗତି କରିବାକୁ ପଡିବ।', HI: 'ओडिशा में सामुदायिक विश्वास ही सब कुछ है। इसीलिए मजदूर लिंक पर प्रत्येक पेशेवर को अपना पहला काम मिलने से पहले भौतिक दस्तावेज़ सत्यापन प्रक्रिया से गुजरना होगा।' },
  safety_point_1: { EN: 'Aadhaar & PAN card background checks', OR: 'ଆଧାର ଏବଂ ପାନ୍ କାର୍ଡ ପୃଷ୍ଠଭୂମି ଯାଞ୍ଚ', HI: 'आधार और पैन कार्ड बैकग्राउंड चेक' },
  safety_point_2: { EN: 'Skill proficiency verification by experts', OR: 'বিଶେଷଜ୍ଞଙ୍କ ଦ୍ୱାରା ଦକ୍ଷତା ଯାଞ୍ଚ', HI: 'विशेषज्ञों द्वारा कौशल दक्षता सत्यापन' },
  safety_point_3: { EN: 'Resident feedback-based quality control', OR: 'ବାସିନ୍ଦାଙ୍କ ମତାମତ ଆଧାରିତ ଗୁଣବତ୍ତା ନିୟନ୍ତ୍ରଣ', HI: 'निवासी फीडबैक-आधारित गुणवत्ता नियंत्रण' },
  safety_point_4: { EN: 'Digital ID card for on-site verification', OR: 'ଅନ-ସାଇଟ୍ ଯାଞ୍ଚ ପାଇଁ ଡିଜିଟାଲ୍ ଆଇଡି କାର୍ଡ', HI: 'ऑन-साइट सत्यापन के लिए डिजिटल आईडी कार्ड' },
  register_now: { EN: 'Register Now', OR: 'ଏବେ ପଞ୍ଜୀକରଣ କରନ୍ତୁ', HI: 'अभी रजिस्टर करें' },
  book_specialist: { EN: 'Book Specialist', OR: 'ବିଶେଷଜ୍ଞ ବୁକ୍ କରନ୍ତୁ', HI: 'विशेषज्ञ बुक करें' },
  login_welcome: { EN: 'Welcome back! Sign in to your account', OR: 'ସ୍ୱାଗତ! ଆପଣଙ୍କ ଆକାଉଣ୍ଟରେ ସାଇନ୍ ଇନ୍ କରନ୍ତୁ', HI: 'वापस स्वागत है! अपने खाते में साइन इन करें' },
  login_subtitle: { EN: 'Enter your credentials to access your account', OR: 'ଆପଣଙ୍କ ଆକାଉଣ୍ଟକୁ ପ୍ରବେଶ କରିବାକୁ ତଥ୍ୟ ଦିଅନ୍ତୁ', HI: 'अपने खाते तक पहुँचने के लिए अपनी क्रेडेंशियल दर्ज करें' },
  remember_me: { EN: 'Remember me', OR: 'ମନେ ରଖନ୍ତୁ', HI: 'मुझे याद रखें' },
  forgot_password: { EN: 'Forgot password?', OR: 'ପାସୱାର୍ଡ ଭୁଲିଯାଇଛନ୍ତି କି?', HI: 'पासवर्ड भूल गए?' },
  no_account: { EN: "Don't have an account?", OR: 'ଆପଣଙ୍କର ଆକାଉଣ୍ଟ୍ ନାହିଁ କି?', HI: 'क्या आपका खाता नहीं है?' },
  sign_up: { EN: 'Sign Up', OR: 'ସାଇନ୍ ଅପ୍', HI: 'साइन अप' },
  customer: { EN: 'Customer', OR: 'ଗ୍ରାହକ', HI: 'ग्राहक' },
  worker: { EN: 'Worker', OR: 'ଶ୍ରମିକ', HI: 'श्रमिक' },
  acc_details: { EN: 'Account Details', OR: 'ଆକାଉଣ୍ଟ୍ ବିବରଣୀ', HI: 'खाता विवरण' },
  security_loc: { EN: 'Security & Location', OR: 'ସୁରକ୍ଷା ଏବଂ ସ୍ଥାନ', HI: 'सुरक्षा और स्थान' },
  kyc_docs: { EN: 'KYC Documents', OR: 'କେୱାଇସି ଦଲିଲ', HI: 'केवाईसी दस्तावेज़' },
  locality_village: { EN: 'Locality/Village', OR: 'ଅଞ୍ଳ/ଗ୍ରାମ', HI: 'इलाका/गाँव' },
  primary_skill: { EN: 'Primary Skill', OR: 'ମୂଖ୍ୟ ଦକ୍ଷତା', HI: 'प्राथमिक कौशल' },
  select_district: { EN: 'Select District', OR: 'ଜିଲ୍ଲା ବାଛନ୍ତୁ', HI: 'जिला चुनें' },
  select_skill: { EN: 'Select Skill', OR: 'ଦକ୍ଷତା ବାଛନ୍ତୁ', HI: 'कौशल चुनें' },
  already_have_account: { EN: 'Already have an account?', OR: 'ପୂର୍ବରୁ ଆକାଉଣ୍ଟ୍ ଅଛି କି?', HI: 'क्या आपके पास पहले से एक खाता है?' },
  join_trusted_network: { EN: "Join Odisha's Trusted Skilled Network", OR: "ଓଡ଼ିଶାର ବିଶ୍ୱସ୍ତ ଦକ୍ଷ ନେଟୱାର୍କରେ ଯୋଗ ଦିଅନ୍ତୁ", HI: "ओडिशा के विश्वसनीय कुशल नेटवर्क से जुड़ें" },
  kyc_photo: { EN: 'Photo', OR: 'ଫଟୋ', HI: 'फोटो' },
  kyc_aadhaar: { EN: 'Aadhaar', OR: 'ଆଧାର', HI: 'आधार' },
  kyc_pan: { EN: 'PAN Card', OR: 'ପାନ୍ କାର୍ଡ', HI: 'पैन कार्ड' },
  kyc_passbook: { EN: 'Passbook', OR: 'ପାସବୁକ୍', HI: 'पासबुक' },
  kyc_uploaded: { EN: 'Uploaded', OR: 'ଅପଲୋଡ୍ ହୋଇଛି', HI: 'अपलोड किया गया' },
  worker_reg_success: { EN: 'Success! You are now live on the platform. Documents are being verified in the background.', OR: 'ସଫଳତା! ଆପଣ ଏବେ ପ୍ଲାଟଫର୍ମରେ ଲାଇଭ୍ ଅଛନ୍ତି | ଦଲିଲଗୁଡ଼ିକ ଯାଞ୍ଚ ଚାଲିଛି |', HI: 'सफलता! अब आप प्लेटफॉर्म पर लाइव हैं। दस्तावेजों का सत्यापन पृष्ठभूमि में किया जा रहा है।' },
  cust_reg_success: { EN: 'Account created successfully!', OR: 'ଆକାଉଣ୍ଟ୍ ସଫଳତାର ସହ ତିଆରି ହେଲା!', HI: 'खाता सफलतापूर्वक बनाया गया!' },
  safety_illustration: { EN: 'https://illustrations.popsy.co/amber/shaking-hands.svg', OR: 'https://illustrations.popsy.co/amber/shaking-hands.svg', HI: 'https://illustrations.popsy.co/amber/shaking-hands.svg' }
};

export const SLIDER_IMAGES = [
  'https://images.unsplash.com/photo-1541963463532-d68292c34b19?auto=format&fit=crop&w=1200&q=80',
  'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=1200&q=80',
  'https://images.unsplash.com/photo-1581094794329-c8112a89af12?auto=format&fit=crop&w=1200&q=80',
];
